### ISSUE TITLE
Improve collapsing forms animations

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/HYPForms#167]
When a form gets collapsed it's contents should flow bellow the header, right now it has goes beyond the header.

**Comment by NSElvis** [comment]
Correct
=====

![correct](https://cloud.githubusercontent.com/assets/1088217/5935717/29cc62b4-a6de-11e4-9642-30f445f5c4df.gif)

Wrong
====

![wrong](https://cloud.githubusercontent.com/assets/1088217/5935719/2eccd406-a6de-11e4-80d5-8c9950e8fcd3.gif)
