### ISSUE TITLE
Make phone_number validation regexp more strict

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/HYPForms#187]
right now is `"[0-9]{8,14}"` but this match something like `"91900143asd"`

so I think it must be changed to `"^[0-9]{8,14}$"` that is more strict on which thing needs to be matched

**Comment by NSElvis** [comment]
@fespinoza nice one!

**Comment by timkurvers** [comment]
Question is whether that should be implied by the client instead. When would you ever not attempt to validate the entire field?

**Comment by fespinoza** [comment]
I was drunk

**Comment by timkurvers** [comment]
It's a great catch though, but I think we might need `^` and `$` everywuuurr. :+1:

**Comment by NSElvis** [comment]
@timkurvers: The idea is that if the field is type `phone_number` we will make this validation by default so you don't have to add it to the JSON, but we haven't work on that yet (would also work for emails and others).

Issue: https://github.com/hyperoslo/HYPForms/issues/130

**Comment by fespinoza** [comment]
@NSElvis that wouldn't work on HTML then
